# fly.toml app configuration file generated for mnist-ml-institute-falling-snowflake-9436 on 2025-03-30T21:38:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mnist-ml-institute'
primary_region = 'lhr'

[build]

[[mounts]]
  source = 'data'
  destination = '/home/pythonuser'
  initial_size = '200gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/_stcore/health"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1GB'